title: "ABE Media"
description: "Wir sind ein kleines, sehr innovatives Web-Design und Entwicklungsunternehmen in Bremen. Seit der Gründung im Jahr 2005 war ABE Media an der Spitze der neuen Technologien und hat die Zukunft des Web-Designs mit jedem Projekt mitgestaltet."
keywords: web design bremen, web development, joomla development, ecommerce
baseurl: /
url: http://abemedia.de
timezone: Europe/Berlin
image: /images/donjoomla.png
locale: de_DE
permalink: /:categories/:title.html
layout: default
disqus_shortname: abemedia
author: Adam Bouqdib
markdown: kramdown
gems:
  - jekyll-sitemap
relative_permalinks: false

facebook_app: 276049565908648
twitter: abemedia
v: 1.3
