name: "ABE Media"
title: "ABE Media &middot; Web Design &amp; Development"
description: "We're a small, yet highly innovative web design and development company based in Brighton &amp; Hove, East Sussex. Since its incorporation in 2005, ABE Media have been at the forefront of new technology, shaping the future of web design with each and every project."
baseurl: /
url: http://abemedia.github.io
timezone: Europe/London
image: /images/donjoomla.png
locale: en_GB
