-
    title: Web Development
    alias: web-design
    url: web-design-bremen
    image: /images/services/web-development.png
    desc: "Wir bieten Ihnen professionelles, innovatives Web-Design &amp; Entwicklung und erstellen barriere-freie, SEO-freundliche Websites, die den Web-Standards gerecht werden."
-
    title: Ecommerce
    alias: ecommerce
    url: ecommerce-web-design
    image: /images/services/ecommerce.png
    desc: "Keine zwei Online-Unternehmen sind gleich; Und deswegen sind unsere Online-Shops komplett auf Ihre individuelle E-Commerce-Strategie angepasst."
-
    title: CMS
    alias: cms
    url: content-management-systems-cms
    image: /images/services/joomla-development.png
    desc: "Unsere CMS-Lösungen werden entwickelt, um die Veröffentlichung Ihrer Inhalte auf Ihrer Website zu vereinfachen, ohne technische Kenntnisse zu erfordern."
-
    title: Mobile Web-Design
    alias: mobile
    url: responsive-web-design
    image: /images/services/mobile-websites.png
    desc: "Dedicated Mobile Sites und responsive Web-Design für Handys & Tablets. Verpassen Sie keine Verkäufe, unabhängig von dem Benutzer-Endgerät."
-
    title: Digitales Marketing
    alias: seo
    url: seo
    image: /images/services/seo.png
    desc: "Effektive SEO & PPC-Kampagnen, um Ihren Traffic zu erhöhen, verbunden mit Conversion-Optimierung, um die Besucher in wiederkehrenden Kunden zu verwandeln."
-
    title: Illustration & 3D
    alias: illustration
    url: illustration
    image: /images/services/illustration.png
    desc: "Zeichnen Sie sich, durch handgemalte oder digitale Kunstwerke und einzigartige animation aus, die perfekt auf Sie zugeschnitten sind."
-
    title: Grafik Design
    alias: graphic
    url: graphic-design
    image: /images/services/illustration.png
    desc: "Von einfachen Logos und Werbematerial wie Broschüren & Visitenkarte bis hin zur vollen Markenidentität.<br>Wir lieben Grafik-Design!"
